### ISSUE TITLE
Easy migrations for dropping tables/columns

### ISSUE THREAD

**Issue by tobyzerner** [franzliedke/laravel-easy-migrations#2]
If the `up` method for a migration is to drop a table or column, then the `down` method would need to re-add that table/column. (Unless there's a better way to do this that I don't know about?)

If that's correct, then we could add `dropTable` and `dropColumns` helpers which take the same arguments as their `create`/`add` counterparts, but swap the `up`/`down` methods:

``` php
    return Easy::dropTable('users', function (Blueprint $table) {
        $table->increments('id');
        $table->string('name');
    });
```

``` php
    return Easy::dropColumns('users', [
        'password' => ['string'],
        'registered_at' => ['dateTime', 'nullable' => true]
    ]);
```

**Comment by franzliedke** [comment]
Thanks for the suggestion, fixed. Will make a new release once this is documented.
